#!/bin/bash
#NODE_PATH=node-src:$NODE_PATH mocha --compilers coffee:coffee-script -w node-spec/

echo compiling...
coffee -c spec/*coffee src/*coffee
echo running jasmine-node
NODE_PATH=src:$NODE_PATH grunt
#NODE_PATH=src:$NODE_PATH jasmine-node --verbose spec/
